In [ ]:
X = []
y = []

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/ppg.csv')

selected_columns_index = [3, 6, 7, 2]
selected_data = df.iloc[:, selected_columns_index]

selected_data.iloc[:, -1] = selected_data.iloc[:, -1].apply(lambda x: 1 if x == 'Female' else 0)

data_array = selected_data.to_numpy()
data_array[0] = data_array[10]  # Just an example modification

# Convert the data array to integers
data_array = data_array.astype(int)




In [ ]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('/content/dsp_data.csv')

# Define the values for the new column
new_column_values = y  # Example values for the new column

# Add the new column to the DataFrame
df['Activity'] = new_column_values

# Define the filename
filename = "dsp_data.csv"

# Write the DataFrame to a CSV file
df.to_csv(filename, index=False)


In [ ]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('/content/dsp_data.csv')

# Select the first four columns as features (X) and the fifth column as target (y)
X = df.iloc[:, :4].values
y = df.iloc[:, 4].values

# Optionally, if you want to convert y to integers, you can do so like this:
# y = y.astype(int)

# Print the first few rows of X and y to verify
print("X (features):")
print(X[:5])  # Printing first 5 rows for demonstration
print("\ny (target):")
print(y[:5])  # Printing first 5 rows for demonstration


X (features):
[[ 47  98  56   1]
 [ 45 161  89   1]
 [ 50 160  93   1]
 [ 47 101  71   1]
 [ 45 136  93   0]]

y (target):
[1 2 1 1 2]


In [ ]:
import numpy as np
import os
from sklearn.utils import shuffle

import librosa
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
X, y = shuffle(X, y, random_state=75)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=75)

clf = RandomForestClassifier(n_estimators=70, random_state=75)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9318181818181818
